
#' Unmapped Concepts -- Output Generation
#'
#' Using the tabular output generated by `uc_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `uc_process`
#'
#' @param output_col *string* || defaults to `NULL`
#'
#'   The name of the numerical variable from `process_output` that should be used to
#'   generate the plot. This input is required for all checks **EXCEPT**
#'   `Multi Site, Anomaly Detection, Longitudinal`
#'
#' @param filter_variable *string or vector* || defaults to `NULL`
#'
#'   A string or vector with variable names that should be the focus of the analysis.
#'   Only a single value is accepted for the following checks:
#'   - `Multi Site, Anomaly Detection, Longitudinal`
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'
#'   Multiple values are accepted for:
#'   - `Multi Site, Exploratory, Cross-Sectional`
#'   - `Multi Site, Exploratory, Longitudinal`
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `uc_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#'
#'
#' @export
#'
uc_output <- function(process_output,
                      output_col,
                      filter_variable = NULL,
                      large_n = FALSE,
                      large_n_sites = NULL){

  output_function <- process_output %>% collect() %>% ungroup() %>%
    distinct(output_function) %>% pull()

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  if(output_function == 'uc_ss_exp_cs'){

    uc_output <- uc_ss_exp_cs(process_output = process_output,
                              output_col = output_col,
                              facet = facet)

  }else if(output_function == 'uc_ss_anom_cs'){

    uc_output <- uc_ss_anom_cs(process_output = process_output,
                               output_col = output_col,
                               facet = facet)

  }else if(output_function == 'uc_ms_exp_cs'){

    uc_output <- uc_ms_exp_cs(process_output = process_output,
                              output_col = output_col,
                              filter_variable = filter_variable,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)

  }else if(output_function == 'uc_ms_anom_cs'){

    uc_output <- uc_ms_anom_cs(process_output = process_output,
                               output_col = output_col,
                               large_n = large_n,
                               large_n_sites = large_n_sites)

  }else if(output_function == 'uc_ss_exp_la'){

    uc_output <- uc_ss_exp_la(process_output = process_output,
                              output_col = output_col,
                              facet = facet)

  }else if(output_function == 'uc_ss_anom_la'){

    uc_output <- uc_ss_anom_la(process_output = process_output,
                               output_col = output_col,
                               filter_variable = filter_variable,
                               facet = facet)

  }else if(output_function == 'uc_ms_exp_la'){

    uc_output <- uc_ms_exp_la(process_output = process_output,
                              output_col = output_col,
                              filter_variable = filter_variable,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)

  }else if(output_function == 'uc_ms_anom_la'){

    uc_output <- uc_ms_anom_la(process_output = process_output,
                               filter_variable = filter_variable,
                               large_n = large_n,
                               large_n_sites = large_n_sites)

  }else(cli::cli_abort('Please enter a valid output function for this check type.'))

  return(uc_output)
}
